services:
  sonarqube:
    image: mc1arke/sonarqube-with-community-branch-plugin:10.3-community
    container_name: sonar-server
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - '9000:9000'
    healthcheck:
      test: wget -qO- http://localhost:9000/api/system/status | grep -q -e '"status":"UP"' -e '"status":"DB_MIGRATION_NEEDED"' -e '"status":"DB_MIGRATION_RUNNING"' > /dev/null
      interval: 5s
      timeout: 5s
      retries: 30
